import React,{useEffect,useMemo,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import L from 'leaflet'
import 'leaflet-draw'
import 'leaflet-draw/dist/leaflet.draw.css'
import {campus,defaultConfig,mergeConfig,RAW_CONFIG_URL} from '../data/runtime.js'
import {normalize} from '../lib.js'

const REPO='dannyvaziri/uafcampusmap'
const CONFIG_FILE='public/map-config.json'
const deepClone=v=>JSON.parse(JSON.stringify(v))
const csv=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean)
const num=v=>v===''?null:Number(v)
const slug=s=>String(s||'item').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||`item-${Date.now()}`
function encode64(str){const bytes=new TextEncoder().encode(str);let out='';for(const b of bytes)out+=String.fromCharCode(b);return btoa(out)}
function Field({label,hint,children}){return <label className="admin-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Switch({label,checked,onChange}){return <label className="admin-switch"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}

const TYPES=[
 ['building','Building','Change a building name, address, services, marker or location.'],
 ['parking','Parking','Change a parking lot name, type, rules or visibility.'],
 ['shape','Shape / area','Draw or edit a polygon, line, point or map area.'],
 ['content','Words','Change public headings, search wording and pilot notices.'],
 ['appearance','Appearance','Change map colors, marker colors and starting map view.'],
 ['layers','Layers','Turn public map sections on/off and choose popular destinations.'],
 ['advanced','Advanced JSON','Edit shuttle, trails, accessibility, construction or other advanced data.']
]

export default function AdminPage(){
 const [step,setStep]=useState(1),[kind,setKind]=useState(''),[config,setConfig]=useState(()=>deepClone(campus.map_config||defaultConfig)),[status,setStatus]=useState('Loading published map settings…')
 const [buildingId,setBuildingId]=useState(campus.buildings[0]?.id||''),[parkingId,setParkingId]=useState(campus.parking[0]?.id||''),[shapeId,setShapeId]=useState(''),[query,setQuery]=useState('')
 const [token,setTokenState]=useState(()=>sessionStorage.getItem('uaf-github-token')||''),[githubStatus,setGithubStatus]=useState(''),[publishing,setPublishing]=useState(false),[advancedText,setAdvancedText]=useState('')
 const mapNode=useRef(null),mapRef=useRef(null),featureGroup=useRef(null),buildingMarker=useRef(null)

 const baseBuildings=campus._base_buildings||campus.buildings,baseParking=campus._base_parking||campus.parking
 const allBuildings=useMemo(()=>{const rows=baseBuildings.map(b=>({...b,...(config.buildingOverrides?.[b.id]||{})}));for(const b of config.customBuildings||[]){const i=rows.findIndex(x=>x.id===b.id);if(i>=0)rows[i]={...rows[i],...b};else rows.push(b)}return rows},[config])
 const allParking=useMemo(()=>{const rows=baseParking.map(p=>({...p,...(config.parkingOverrides?.[p.id]||{})}));for(const p of config.customParking||[]){const i=rows.findIndex(x=>x.id===p.id);if(i>=0)rows[i]={...rows[i],...p};else rows.push(p)}return rows},[config])
 const building=allBuildings.find(b=>b.id===buildingId),parking=allParking.find(p=>p.id===parkingId),shape=config.shapes.find(s=>s.properties?.id===shapeId)
 const filteredBuildings=allBuildings.filter(b=>normalize(`${b.common_name} ${b.official_name} ${b.address} ${b.abbreviation}`).includes(normalize(query)))
 const filteredParking=allParking.filter(p=>normalize(`${p.code} ${p.name} ${p.restrictions}`).includes(normalize(query)))

 useEffect(()=>{(async()=>{try{const r=await fetch(`${RAW_CONFIG_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error();const next=mergeConfig(defaultConfig,await r.json());setConfig(next);setAdvancedText(JSON.stringify(next,null,2));setStatus('Published GitHub configuration loaded.')}catch(e){const next=mergeConfig(defaultConfig,campus.map_config||{});setConfig(next);setAdvancedText(JSON.stringify(next,null,2));setStatus('Using the configuration bundled with this deployment.')}})()},[])
 useEffect(()=>{setAdvancedText(JSON.stringify(config,null,2))},[config])

 function setToken(v){setTokenState(v);if(v)sessionStorage.setItem('uaf-github-token',v);else sessionStorage.removeItem('uaf-github-token')}
 function updateSetting(section,key,value){setConfig(c=>({...c,settings:{...c.settings,[section]:{...(c.settings?.[section]||{}),[key]:value}}}))}
 function updateRoot(key,value){setConfig(c=>({...c,settings:{...c.settings,[key]:value}}))}
 function updateBuilding(field,value){if(!buildingId)return;setConfig(c=>{const custom=(c.customBuildings||[]).some(b=>b.id===buildingId);if(custom)return {...c,customBuildings:c.customBuildings.map(b=>b.id===buildingId?{...b,[field]:value}:b)};return {...c,buildingOverrides:{...c.buildingOverrides,[buildingId]:{...(c.buildingOverrides?.[buildingId]||{}),[field]:value}}}})}
 function updateParking(field,value){if(!parkingId)return;setConfig(c=>{const custom=(c.customParking||[]).some(p=>p.id===parkingId);if(custom)return {...c,customParking:c.customParking.map(p=>p.id===parkingId?{...p,[field]:value}:p)};return {...c,parkingOverrides:{...c.parkingOverrides,[parkingId]:{...(c.parkingOverrides?.[parkingId]||{}),[field]:value}}}})}
 function updateShape(field,value){if(!shapeId)return;setConfig(c=>({...c,shapes:c.shapes.map(s=>s.properties?.id===shapeId?{...s,properties:{...(s.properties||{}),[field]:value}}:s)}))}
 function choose(type){setKind(type);setStep(2);setQuery('');setStatus(`Step 2: edit ${TYPES.find(x=>x[0]===type)?.[1].toLowerCase()||'item'}.`)}
 function review(){setStep(3);setStatus('Step 3: review and publish. Publishing commits only map configuration to GitHub.')}
 function startOver(){setStep(1);setKind('');setQuery('');setStatus('Choose what you want to edit.')}
 function saveDraft(){localStorage.setItem('uaf-map-admin-draft',JSON.stringify(config));setStatus('Draft saved in this browser. It is not public yet.')}
 function loadDraft(){try{const x=JSON.parse(localStorage.getItem('uaf-map-admin-draft'));setConfig(mergeConfig(defaultConfig,x));setStatus('Browser draft loaded.')}catch(e){setStatus('No valid saved draft was found.') }}
 function addBuilding(){const center=config.settings.map?.center||[64.857,-147.829],id=`custom-building-${Date.now().toString().slice(-7)}`;const b={id,official_name:'New building',common_name:'New building',abbreviation:'',category:'service',address:'',latitude:center[0],longitude:center[1],geometry_status:'admin custom — verify UAF GIS',source_url:'',services:[],search_terms:[],recommended_parking:[],marker_label:'',marker_color:config.settings.colors.marker,visible:true};setConfig(c=>({...c,customBuildings:[...(c.customBuildings||[]),b]}));setBuildingId(id);setStatus('New building added to the draft.')}
 function addParking(){const id=`custom-parking-${Date.now().toString().slice(-7)}`,p={id,code:'NEW',name:'New parking area',type:'permit_pay_by_plate',restrictions:'',visible:true};setConfig(c=>({...c,customParking:[...(c.customParking||[]),p]}));setParkingId(id);setStatus('New parking area added to the draft.')}
 function applyAdvanced(){try{setConfig(mergeConfig(defaultConfig,JSON.parse(advancedText)));setStatus('Advanced JSON applied to the draft.')}catch(e){setStatus(`JSON error: ${e.message}`)}}

 useEffect(()=>{
  if(step!==2||!['building','shape'].includes(kind)||!mapNode.current)return
  const center=config.settings.map?.center||[64.857,-147.829],zoom=Number(config.settings.map?.zoom||16)
  const map=L.map(mapNode.current,{center,zoom,keyboard:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);mapRef.current=map
  const fg=new L.FeatureGroup().addTo(map);featureGroup.current=fg
  if(kind==='shape'){
   const draw=new L.Control.Draw({position:'topright',edit:{featureGroup:fg,remove:true},draw:{polygon:true,polyline:true,rectangle:true,marker:true,circle:false,circlemarker:false}});map.addControl(draw)
   map.on(L.Draw.Event.CREATED,e=>{const f=e.layer.toGeoJSON();f.properties={id:`shape-${Date.now()}`,name:`New ${e.layerType}`,kind:e.layerType,visible:true,stroke:config.settings.colors.blue,fill:config.settings.colors.blue,weight:3,opacity:.9,fillOpacity:.14};setConfig(c=>({...c,shapes:[...(c.shapes||[]),f]}));setShapeId(f.properties.id);setStatus('Shape added. Name and style it below.')})
   map.on(L.Draw.Event.EDITED,e=>{const changes={};e.layers.eachLayer(layer=>{const id=layer.feature?.properties?.id;if(id){const g=layer.toGeoJSON();g.properties={...layer.feature.properties};changes[id]=g}});setConfig(c=>({...c,shapes:c.shapes.map(s=>changes[s.properties?.id]||s)}))})
   map.on(L.Draw.Event.DELETED,e=>{const ids=new Set();e.layers.eachLayer(layer=>layer.feature?.properties?.id&&ids.add(layer.feature.properties.id));setConfig(c=>({...c,shapes:c.shapes.filter(s=>!ids.has(s.properties?.id))}))})
  }else{
   map.on('click',e=>{updateBuilding('latitude',Number(e.latlng.lat.toFixed(7)));updateBuilding('longitude',Number(e.latlng.lng.toFixed(7)));setStatus('Building location moved to the clicked map point.')})
  }
  return()=>{map.remove();mapRef.current=null;featureGroup.current=null;buildingMarker.current=null}
 },[step,kind])

 useEffect(()=>{
  if(step!==2||kind!=='shape'||!mapRef.current||!featureGroup.current)return
  featureGroup.current.clearLayers()
  L.geoJSON({type:'FeatureCollection',features:config.shapes||[]},{style:f=>({color:f.properties?.stroke||config.settings.colors.blue,weight:Number(f.properties?.weight||3),opacity:Number(f.properties?.opacity??.9),fillColor:f.properties?.fill||f.properties?.stroke||config.settings.colors.blue,fillOpacity:Number(f.properties?.fillOpacity??.14)}),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:f.properties?.stroke||config.settings.colors.blue,fillColor:f.properties?.fill||config.settings.colors.blue,fillOpacity:.8}),onEachFeature:(f,l)=>{l.feature=f;if(f.properties?.name)l.bindTooltip(f.properties.name);l.on('click',()=>setShapeId(f.properties?.id||''))}}).eachLayer(l=>featureGroup.current.addLayer(l))
 },[config.shapes,step,kind])

 useEffect(()=>{
  if(step!==2||kind!=='building'||!mapRef.current||!building)return
  if(buildingMarker.current){mapRef.current.removeLayer(buildingMarker.current);buildingMarker.current=null}
  const lat=Number(building.latitude),lon=Number(building.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return
  const m=L.marker([lat,lon],{draggable:true,title:`Move ${building.common_name||'building'}`}).addTo(mapRef.current).bindTooltip('Drag this marker, or click the map, to reposition the building')
  m.on('dragend',()=>{const p=m.getLatLng();updateBuilding('latitude',Number(p.lat.toFixed(7)));updateBuilding('longitude',Number(p.lng.toFixed(7)));setStatus('Building location updated in the draft.')});buildingMarker.current=m;mapRef.current.panTo([lat,lon])
 },[buildingId,building?.latitude,building?.longitude,step,kind])

 async function connectGithub(){if(!token.trim()){setGithubStatus('Paste a fine-grained GitHub token first.');return false}setGithubStatus('Connecting…');try{const r=await fetch(`https://api.github.com/repos/${REPO}`,{headers:{Authorization:`Bearer ${token.trim()}`,Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`GitHub returned ${r.status}`);const j=await r.json();if(!j.permissions?.push)throw new Error('This token can read the repo but cannot publish. Give it Contents: Read and write.');setGithubStatus('Connected to GitHub. This browser session can publish map changes.');return true}catch(e){setGithubStatus(e.message);return false}}
 async function publish(){setPublishing(true);try{if(!(await connectGithub()))return;setGithubStatus('Publishing map configuration to GitHub…');const headers={Authorization:`Bearer ${token.trim()}`,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'};const get=await fetch(`https://api.github.com/repos/${REPO}/contents/${CONFIG_FILE}?ref=main`,{headers});if(!get.ok)throw new Error(`Could not read current map configuration (${get.status}).`);const current=await get.json();const message=`Update UAF campus map: ${TYPES.find(x=>x[0]===kind)?.[1]||'settings'}`;const put=await fetch(`https://api.github.com/repos/${REPO}/contents/${CONFIG_FILE}`,{method:'PUT',headers,body:JSON.stringify({message,content:encode64(JSON.stringify(config,null,2)+'\n'),sha:current.sha,branch:'main'})});if(!put.ok){const err=await put.json().catch(()=>({}));throw new Error(err.message||`GitHub publish failed (${put.status}).`)}localStorage.removeItem('uaf-map-admin-draft');setGithubStatus('Published. The public map now reads this GitHub configuration automatically, and Hostinger will also redeploy from main.');setStatus('Published successfully. Your change is now in GitHub.')}catch(e){setGithubStatus(e.message)}finally{setPublishing(false)}}

 const typeLabel=TYPES.find(x=>x[0]===kind)?.[1]||'Edit'
 return <main id="main-content" className="page admin-page simple-admin">
  <div className="admin-title-row"><div><p className="eyebrow">UAF CAMPUS MAP</p><h1>Simple map editor</h1><p>Choose it. Change it. Publish it.</p></div><div className="admin-actions"><Link className="button-link" to="/">Open public map</Link><button type="button" onClick={saveDraft}>Save draft</button></div></div>
  <div className="wizard-steps" aria-label="Editing progress"><button type="button" className={step===1?'current':step>1?'done':''} onClick={()=>setStep(1)}><span>1</span><strong>Choose</strong><small>What do you want to edit?</small></button><button type="button" className={step===2?'current':step>2?'done':''} disabled={!kind} onClick={()=>kind&&setStep(2)}><span>2</span><strong>Edit</strong><small>Make the change.</small></button><button type="button" className={step===3?'current':''} disabled={!kind} onClick={()=>kind&&review()}><span>3</span><strong>Publish</strong><small>Update GitHub + public map.</small></button></div>
  <div className="admin-status" role="status" aria-live="polite">{status}</div>

  {step===1&&<section className="wizard-panel"><div className="wizard-heading"><p className="eyebrow">STEP 1</p><h2>What do you want to edit?</h2><p>Pick one. You can come back and edit something else immediately after publishing.</p></div><div className="edit-choice-grid">{TYPES.map(([id,label,desc])=><button key={id} type="button" onClick={()=>choose(id)}><span className="choice-arrow">→</span><strong>{label}</strong><small>{desc}</small></button>)}</div><div className="draft-row"><button type="button" onClick={loadDraft}>Load saved browser draft</button><a href={`https://github.com/${REPO}`} target="_blank" rel="noreferrer">Open GitHub repository</a></div></section>}

  {step===2&&<section className="wizard-panel"><div className="wizard-heading"><p className="eyebrow">STEP 2</p><h2>Edit {typeLabel.toLowerCase()}</h2><p>Only the fields you change are saved as map overrides.</p></div>
   {kind==='building'&&<><div className="quick-select"><div><label htmlFor="building-search">Find a building</label><input id="building-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search building name or address…"/></div><button type="button" onClick={addBuilding}>+ Add new building</button></div><div className="simple-list-picker">{filteredBuildings.slice(0,80).map(b=><button key={b.id} type="button" className={buildingId===b.id?'selected':''} onClick={()=>setBuildingId(b.id)}><strong>{b.common_name}</strong><small>{b.address||'No address'}</small></button>)}</div>{building&&<div className="simple-edit-card"><h3>{building.common_name}</h3><div className="admin-grid two"><Field label="Public name"><input value={building.common_name||''} onChange={e=>updateBuilding('common_name',e.target.value)}/></Field><Field label="Abbreviation"><input value={building.abbreviation||''} maxLength="12" onChange={e=>updateBuilding('abbreviation',e.target.value)}/></Field><Field label="Address"><input value={building.address||''} onChange={e=>updateBuilding('address',e.target.value)}/></Field><Field label="Category"><input value={building.category||''} onChange={e=>updateBuilding('category',e.target.value)}/></Field><Field label="Services" hint="Separate with commas"><input value={(building.services||[]).join(', ')} onChange={e=>updateBuilding('services',csv(e.target.value))}/></Field><Field label="Search words" hint="Separate with commas"><input value={(building.search_terms||[]).join(', ')} onChange={e=>updateBuilding('search_terms',csv(e.target.value))}/></Field><Field label="Recommended parking" hint="Lot codes, separated with commas"><input value={(building.recommended_parking||[]).join(', ')} onChange={e=>updateBuilding('recommended_parking',csv(e.target.value))}/></Field><Field label="Marker text" hint="Four characters or fewer works best"><input value={building.marker_label||''} maxLength="8" onChange={e=>updateBuilding('marker_label',e.target.value)}/></Field><Field label="Marker color"><input type="color" value={building.marker_color||config.settings.colors.marker} onChange={e=>updateBuilding('marker_color',e.target.value)}/></Field><Switch label="Show this building publicly" checked={building.visible!==false} onChange={v=>updateBuilding('visible',v)}/></div><p className="admin-help">Location: drag the marker or click the map. You can also enter coordinates below.</p><div className="admin-grid two"><Field label="Latitude"><input type="number" step="0.0000001" value={building.latitude??''} onChange={e=>updateBuilding('latitude',num(e.target.value))}/></Field><Field label="Longitude"><input type="number" step="0.0000001" value={building.longitude??''} onChange={e=>updateBuilding('longitude',num(e.target.value))}/></Field></div></div>}<div ref={mapNode} className="admin-map" aria-label="Building location editor map"/></>}

   {kind==='parking'&&<><div className="quick-select"><div><label htmlFor="parking-search">Find parking</label><input id="parking-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search lot code, name or rule…"/></div><button type="button" onClick={addParking}>+ Add parking area</button></div><div className="simple-list-picker">{filteredParking.map(p=><button key={p.id} type="button" className={parkingId===p.id?'selected':''} onClick={()=>setParkingId(p.id)}><strong>{p.code} — {p.name}</strong><small>{p.restrictions}</small></button>)}</div>{parking&&<div className="simple-edit-card"><h3>{parking.code} — {parking.name}</h3><div className="admin-grid two"><Field label="Lot code"><input value={parking.code||''} onChange={e=>updateParking('code',e.target.value)}/></Field><Field label="Public name"><input value={parking.name||''} onChange={e=>updateParking('name',e.target.value)}/></Field><Field label="Type"><input value={parking.type||''} onChange={e=>updateParking('type',e.target.value)}/></Field><Field label="Rules / restrictions"><textarea rows="4" value={parking.restrictions||''} onChange={e=>updateParking('restrictions',e.target.value)}/></Field><Switch label="Show this parking record publicly" checked={parking.visible!==false} onChange={v=>updateParking('visible',v)}/></div></div>}</>}

   {kind==='shape'&&<div className="shape-simple-grid"><div ref={mapNode} className="admin-map tall" aria-label="Shape drawing map"/><div className="simple-edit-card"><h3>Draw or edit a shape</h3><p>Use the drawing buttons on the map. Click a shape to select it.</p><Field label="Selected shape"><select value={shapeId} onChange={e=>setShapeId(e.target.value)}><option value="">Select a shape…</option>{config.shapes.map(s=><option key={s.properties?.id} value={s.properties?.id}>{s.properties?.name||s.properties?.id}</option>)}</select></Field>{shape&&<div className="shape-fields"><Field label="Name"><input value={shape.properties?.name||''} onChange={e=>updateShape('name',e.target.value)}/></Field><Field label="Line color"><input type="color" value={shape.properties?.stroke||config.settings.colors.blue} onChange={e=>updateShape('stroke',e.target.value)}/></Field><Field label="Fill color"><input type="color" value={shape.properties?.fill||shape.properties?.stroke||config.settings.colors.blue} onChange={e=>updateShape('fill',e.target.value)}/></Field><Field label="Line width"><input type="range" min="1" max="10" value={shape.properties?.weight||3} onChange={e=>updateShape('weight',Number(e.target.value))}/></Field><Field label="Fill opacity"><input type="range" min="0" max="1" step=".05" value={shape.properties?.fillOpacity??.14} onChange={e=>updateShape('fillOpacity',Number(e.target.value))}/></Field><Field label="Associate with building"><select value={shape.properties?.building_id||''} onChange={e=>updateShape('building_id',e.target.value)}><option value="">None</option>{allBuildings.map(b=><option key={b.id} value={b.id}>{b.common_name}</option>)}</select></Field><Switch label="Show this shape publicly" checked={shape.properties?.visible!==false} onChange={v=>updateShape('visible',v)}/></div>}</div></div>}

   {kind==='content'&&<div className="simple-edit-card"><h3>Public words</h3><div className="admin-grid two"><Field label="Site title"><input value={config.settings.siteTitle||''} onChange={e=>updateRoot('siteTitle',e.target.value)}/></Field><Field label="Site subtitle"><input value={config.settings.siteSubtitle||''} onChange={e=>updateRoot('siteSubtitle',e.target.value)}/></Field><Field label="Pilot notice heading"><input value={config.settings.pilotTitle||''} onChange={e=>updateRoot('pilotTitle',e.target.value)}/></Field><Field label="Search label"><input value={config.settings.labels.searchLabel||''} onChange={e=>updateSetting('labels','searchLabel',e.target.value)}/></Field><Field label="Search placeholder"><input value={config.settings.labels.searchPlaceholder||''} onChange={e=>updateSetting('labels','searchPlaceholder',e.target.value)}/></Field><Field label="Search button"><input value={config.settings.labels.searchButton||''} onChange={e=>updateSetting('labels','searchButton',e.target.value)}/></Field><Field label="Popular destinations heading"><input value={config.settings.labels.popularHeading||''} onChange={e=>updateSetting('labels','popularHeading',e.target.value)}/></Field><Field label="All places heading"><input value={config.settings.labels.allPlacesHeading||''} onChange={e=>updateSetting('labels','allPlacesHeading',e.target.value)}/></Field></div><Field label="Public pilot / accessibility notice"><textarea rows="5" value={config.settings.pilotNotice||''} onChange={e=>updateRoot('pilotNotice',e.target.value)}/></Field></div>}

   {kind==='appearance'&&<div className="simple-edit-card"><h3>Appearance</h3><p className="brand-warning"><strong>UAF brand defaults:</strong> blue #236192 and gold #FFCD00. Change them only when you intentionally want a nonstandard preview.</p><div className="admin-grid three">{[['blue','UAF blue'],['gold','UAF gold'],['marker','Building markers'],['parking','Parking'],['access','Accessibility'],['trail','Trails'],['closure','Closures']].map(([key,label])=><Field key={key} label={label}><input type="color" value={config.settings.colors[key]} onChange={e=>updateSetting('colors',key,e.target.value)}/></Field>)}</div><h3>Starting map view</h3><div className="admin-grid three"><Field label="Latitude"><input type="number" step=".000001" value={config.settings.map.center[0]} onChange={e=>updateSetting('map','center',[Number(e.target.value),config.settings.map.center[1]])}/></Field><Field label="Longitude"><input type="number" step=".000001" value={config.settings.map.center[1]} onChange={e=>updateSetting('map','center',[config.settings.map.center[0],Number(e.target.value)])}/></Field><Field label="Zoom"><input type="number" min="10" max="20" value={config.settings.map.zoom} onChange={e=>updateSetting('map','zoom',Number(e.target.value))}/></Field></div></div>}

   {kind==='layers'&&<div className="simple-edit-card"><h3>Public layers</h3><div className="switch-grid">{[['search','Search'],['parking','Parking'],['access','Access'],['shuttle','Shuttle'],['trails','Trails'],['updates','Updates']].map(([id,label])=><Switch key={id} label={label} checked={config.settings.tabs[id]} onChange={v=>updateSetting('tabs',id,v)}/>)}</div><h3>Popular destinations</h3><p>Check the buildings that should appear first when the search is empty.</p><div className="popular-admin-list">{allBuildings.map(b=><Switch key={b.id} label={b.common_name} checked={(config.settings.popularIds||[]).includes(b.id)} onChange={checked=>setConfig(c=>({...c,settings:{...c.settings,popularIds:checked?[...(c.settings.popularIds||[]),b.id]:(c.settings.popularIds||[]).filter(id=>id!==b.id)}}))}/>)}</div></div>}

   {kind==='advanced'&&<div className="simple-edit-card"><h3>Advanced JSON</h3><p>Use this only for data not covered by the simple editors, such as Shuttle, Trails, Accessibility, Construction, parking policy or bulk changes.</p><textarea className="json-editor" value={advancedText} onChange={e=>setAdvancedText(e.target.value)} spellCheck="false"/><div className="button-row"><button type="button" onClick={applyAdvanced}>Apply JSON to draft</button></div></div>}

   <div className="wizard-bottom"><button type="button" onClick={()=>setStep(1)}>← Back</button><button type="button" onClick={saveDraft}>Save draft</button><button type="button" className="primary-admin next-step" onClick={review}>Review & publish →</button></div>
  </section>}

  {step===3&&<section className="wizard-panel publish-simple"><div className="wizard-heading"><p className="eyebrow">STEP 3</p><h2>Review and publish</h2><p>One click commits the current map configuration to GitHub. The public map reads that file automatically, and Hostinger is connected to the same <code>main</code> branch.</p></div><div className="publish-summary"><div><span>Editing</span><strong>{typeLabel}</strong></div>{kind==='building'&&building&&<div><span>Building</span><strong>{building.common_name}</strong></div>}{kind==='parking'&&parking&&<div><span>Parking</span><strong>{parking.code} — {parking.name}</strong></div>}{kind==='shape'&&shape&&<div><span>Shape</span><strong>{shape.properties?.name||shape.properties?.id}</strong></div>}<div><span>GitHub</span><strong>{REPO} · main</strong></div></div><div className="github-connect-card"><p className="eyebrow">GITHUB CONNECTION</p><h3>{token?'GitHub token ready':'Connect once for this browser session'}</h3><p>Your token is kept only in session storage and is cleared when the browser session ends. It is never written into the repository or public map configuration.</p><Field label="Fine-grained GitHub token" hint="Repository access: uafcampusmap. Permission: Contents — Read and write."><input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="github_pat_…"/></Field><div className="button-row"><button type="button" onClick={connectGithub}>Test GitHub connection</button><a href={`https://github.com/${REPO}`} target="_blank" rel="noreferrer">Open repository</a></div><p className="github-status" role="status" aria-live="polite">{githubStatus}</p></div><div className="publish-explain"><strong>What happens when you publish?</strong><ol><li>The editor updates <code>public/map-config.json</code> in GitHub.</li><li>The public map loads the new GitHub configuration automatically.</li><li>Hostinger sees the <code>main</code> commit and redeploys the app automatically.</li></ol></div><div className="wizard-bottom"><button type="button" onClick={()=>setStep(2)}>← Keep editing</button><button type="button" className="primary-admin publish-now" disabled={publishing} onClick={publish}>{publishing?'Publishing…':'Publish to GitHub & update map'}</button><button type="button" onClick={startOver}>Edit something else</button></div></section>}
 </main>
}
