import React,{useEffect,useMemo,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import L from 'leaflet'
import {campus,defaultConfig,mergeConfig,RAW_CONFIG_URL} from '../data/runtime.js'

const REPO='dannyvaziri/uafcampusmap',CONFIG_FILE='public/map-config.json'
const clone=v=>JSON.parse(JSON.stringify(v))
function encode64(str){const bytes=new TextEncoder().encode(str);let out='';for(const b of bytes)out+=String.fromCharCode(b);return btoa(out)}
function Field({label,children,hint}){return <label className="admin-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

export default function ImageOverlayPage(){
 const [config,setConfig]=useState(()=>clone(campus.map_config||defaultConfig)),[selectedId,setSelectedId]=useState(''),[status,setStatus]=useState('Upload a PNG to begin.'),[token,setTokenState]=useState(()=>sessionStorage.getItem('uaf-github-token')||''),[publishing,setPublishing]=useState(false)
 const mapNode=useRef(null),mapRef=useRef(null),layerRef=useRef(null),handleGroup=useRef(null)
 const overlays=config.imageOverlays||[],selected=useMemo(()=>overlays.find(x=>x.id===selectedId)||null,[overlays,selectedId])
 useEffect(()=>{if(!selectedId&&overlays[0])setSelectedId(overlays[0].id)},[overlays,selectedId])
 useEffect(()=>{(async()=>{try{const r=await fetch(`${RAW_CONFIG_URL}?v=${Date.now()}`,{cache:'no-store'});if(r.ok){const next=mergeConfig(defaultConfig,await r.json());setConfig(next);if(next.imageOverlays?.[0])setSelectedId(next.imageOverlays[0].id)}}catch(e){}})()},[])
 useEffect(()=>{if(!mapNode.current||mapRef.current)return;const center=config.settings?.map?.center||[64.857,-147.829],zoom=Number(config.settings?.map?.zoom||16);const map=L.map(mapNode.current,{center,zoom,keyboard:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(map);handleGroup.current=L.layerGroup().addTo(map);mapRef.current=map;setTimeout(()=>map.invalidateSize(),0);return()=>{map.remove();mapRef.current=null}},[])
 useEffect(()=>{renderSelected()},[selectedId,selected?.bounds?.[0]?.[0],selected?.bounds?.[0]?.[1],selected?.bounds?.[1]?.[0],selected?.bounds?.[1]?.[1],selected?.opacity,selected?.dataUrl])
 function setToken(v){setTokenState(v);if(v)sessionStorage.setItem('uaf-github-token',v);else sessionStorage.removeItem('uaf-github-token')}
 function update(id,patch){setConfig(c=>({...c,imageOverlays:(c.imageOverlays||[]).map(x=>x.id===id?{...x,...patch}:x)}))}
 function renderSelected(){const map=mapRef.current;if(!map)return;if(layerRef.current){map.removeLayer(layerRef.current);layerRef.current=null}handleGroup.current?.clearLayers();if(!selected?.dataUrl||!selected?.bounds)return;const bounds=L.latLngBounds(selected.bounds);layerRef.current=L.imageOverlay(selected.dataUrl,bounds,{opacity:Number(selected.opacity??.8),interactive:false,zIndex:450}).addTo(map);map.fitBounds(bounds.pad(.8),{maxZoom:19});const sw=bounds.getSouthWest(),ne=bounds.getNorthEast(),center=bounds.getCenter();const icon=L.divIcon({className:'overlay-resize-handle',html:'',iconSize:[18,18],iconAnchor:[9,9]});const centerIcon=L.divIcon({className:'overlay-move-handle',html:'↕',iconSize:[30,30],iconAnchor:[15,15]});const swm=L.marker(sw,{draggable:true,icon,title:'Resize southwest corner'}).addTo(handleGroup.current),nem=L.marker(ne,{draggable:true,icon,title:'Resize northeast corner'}).addTo(handleGroup.current),cm=L.marker(center,{draggable:true,icon:centerIcon,title:'Move image'}).addTo(handleGroup.current);const saveCorners=()=>{const a=swm.getLatLng(),b=nem.getLatLng();update(selected.id,{bounds:[[Math.min(a.lat,b.lat),Math.min(a.lng,b.lng)],[Math.max(a.lat,b.lat),Math.max(a.lng,b.lng)]]});setStatus('Image resized in the draft.')};swm.on('dragend',saveCorners);nem.on('dragend',saveCorners);cm.on('dragstart',()=>{cm._start=cm.getLatLng()});cm.on('dragend',()=>{const end=cm.getLatLng(),start=cm._start||center,dLat=end.lat-start.lat,dLng=end.lng-start.lng;update(selected.id,{bounds:[[sw.lat+dLat,sw.lng+dLng],[ne.lat+dLat,ne.lng+dLng]]});setStatus('Image moved in the draft.')})}
 function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.type!=='image/png'){setStatus('Please choose a PNG file.');return}if(file.size>2_000_000){setStatus('PNG is larger than 2 MB. Reduce the file size before uploading so publishing stays reliable.');return}const reader=new FileReader();reader.onload=()=>{const center=mapRef.current?.getCenter()||L.latLng(config.settings?.map?.center||[64.857,-147.829]),id=`png-${Date.now()}`,lat=.00045,lng=.001;const item={id,name:file.name.replace(/\.png$/i,''),dataUrl:reader.result,bounds:[[center.lat-lat,center.lng-lng],[center.lat+lat,center.lng+lng]],opacity:.85,visible:true};setConfig(c=>({...c,imageOverlays:[...(c.imageOverlays||[]),item]}));setSelectedId(id);setStatus('PNG uploaded. Drag the center handle to move it and corner handles to resize it.')};reader.readAsDataURL(file)}
 function remove(){if(!selected)return;setConfig(c=>({...c,imageOverlays:(c.imageOverlays||[]).filter(x=>x.id!==selected.id)}));setSelectedId('');setStatus('PNG removed from the draft.')}
 async function publish(){if(!token.trim()){setStatus('Enter your GitHub token first.');return}setPublishing(true);setStatus('Publishing PNG overlay to GitHub…');try{const headers={Authorization:`Bearer ${token.trim()}`,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'};const get=await fetch(`https://api.github.com/repos/${REPO}/contents/${CONFIG_FILE}?ref=main`,{headers});if(!get.ok)throw new Error(`Could not read current map config (${get.status}).`);const current=await get.json(),body=JSON.stringify(config,null,2)+'\n';const put=await fetch(`https://api.github.com/repos/${REPO}/contents/${CONFIG_FILE}`,{method:'PUT',headers,body:JSON.stringify({message:'Update UAF map PNG overlays',content:encode64(body),sha:current.sha,branch:'main'})});if(!put.ok){const err=await put.json().catch(()=>({}));throw new Error(err.message||`GitHub publish failed (${put.status}).`)}const result=await put.json(),sha=result.commit?.sha||'';localStorage.setItem('uaf-map-live-config',JSON.stringify({time:Date.now(),config,sha}));localStorage.setItem('uaf-map-live-refresh',String(Date.now()));if('BroadcastChannel'in window){const bc=new BroadcastChannel('uaf-map-live');bc.postMessage({type:'published',sha});bc.close()}setStatus('Published. The PNG overlay is now part of the live map configuration and Hostinger will redeploy automatically.')}catch(e){setStatus(e.message)}finally{setPublishing(false)}}
 return <main id="main-content" className="page admin-page image-overlay-page"><div className="admin-title-row"><div><p className="eyebrow">UAF CAMPUS MAP ADMIN</p><h1>PNG image overlays</h1><p>Upload → place & resize → publish live.</p></div><div className="admin-actions"><Link className="button-link" to="/admin">Back to admin</Link><Link className="button-link" to="/">Public map</Link></div></div><div className="admin-status" role="status" aria-live="polite">{status}</div><div className="overlay-admin-layout"><section className="overlay-controls"><div className="overlay-step"><strong>1. Upload PNG</strong><label className="file-button overlay-upload">Choose PNG<input type="file" accept="image/png,.png" onChange={upload}/></label><small>Transparent PNGs work best. Maximum 2 MB.</small></div><div className="overlay-step"><strong>2. Select & adjust</strong><Field label="Overlay"><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select an overlay…</option>{overlays.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>{selected&&<><Field label="Name"><input value={selected.name||''} onChange={e=>update(selected.id,{name:e.target.value})}/></Field><Field label={`Opacity ${Math.round(Number(selected.opacity??.85)*100)}%`}><input type="range" min="0.05" max="1" step="0.05" value={selected.opacity??.85} onChange={e=>update(selected.id,{opacity:Number(e.target.value)})}/></Field><label className="admin-switch"><input type="checkbox" checked={selected.visible!==false} onChange={e=>update(selected.id,{visible:e.target.checked})}/><span>Show on public map</span></label><button type="button" className="danger" onClick={remove}>Delete overlay</button></>}</div><div className="overlay-step"><strong>3. Publish live</strong><Field label="GitHub token"><input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="github_pat_…"/></Field><button type="button" className="primary-admin overlay-publish" disabled={publishing||!overlays.length} onClick={publish}>{publishing?'Publishing…':'Publish PNG overlays'}</button></div></section><section className="overlay-map-card"><div className="builder-tip"><strong>Move:</strong> drag the round center handle. <strong>Resize:</strong> drag either square corner handle.</div><div ref={mapNode} className="overlay-map" aria-label="PNG overlay placement map"/></section></div></main>
}
