import React,{useEffect} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {QRCodeSVG} from 'qrcode.react'
import {campus} from '../data/index.js'
import {exactPoint,popularIds} from '../lib.js'

const templates={visitor:{label:'8.5×11 visitor map',paper:'letter'},full:{label:'11×17 full campus map',paper:'ledger'},accessibility:{label:'8.5×11 accessibility map',paper:'letter'},event:{label:'Event-specific map',paper:'letter'},bw:{label:'Black-and-white office map',paper:'letter'},directions:{label:'Directional handout',paper:'letter'}}
export default function PrintPage(){const[params,setParams]=useSearchParams();const template=templates[params.get('template')]?params.get('template'):'visitor';const place=params.get('place')||'signers';const building=campus.buildings.find(b=>b.id===place)||campus.buildings[0];const paper=templates[template].paper;useEffect(()=>{document.body.dataset.printPaper=paper;return()=>{delete document.body.dataset.printPaper}},[paper]);function setTemplate(v){const n=new URLSearchParams(params);n.set('template',v);if(v!=='directions')n.delete('place');setParams(n)}function setPlace(v){const n=new URLSearchParams(params);n.set('template','directions');n.set('place',v);setParams(n)}return <main id="main-content" className="print-page"><div className="print-tools" aria-label="Print controls"><Link to="/">Back to map</Link><label>Template<select value={template} onChange={e=>setTemplate(e.target.value)}>{Object.entries(templates).map(([k,v])=><option value={k} key={k}>{v.label}</option>)}</select></label>{template==='directions'&&<label>Destination<select value={building.id} onChange={e=>setPlace(e.target.value)}>{campus.buildings.map(b=><option key={b.id} value={b.id}>{b.common_name}</option>)}</select></label>}<button type="button" className="print-button" onClick={()=>window.print()}>Print / Save PDF</button></div><Sheet template={template} building={building}/></main>}
function Sheet({template,building}){const full=template==='full',bw=template==='bw',visitor=campus.parking.filter(p=>p.type==='visitor_short_term').slice(0,8);return <article className={`print-sheet ${full?'ledger':'letter'} ${bw?'bw':''}`}><header><div><span>UNIVERSITY OF ALASKA FAIRBANKS</span><h1>{templates[template].label}</h1></div><div>Updated Sept. 1, 2026<br/>uaf.edu/campusmap</div></header><div className="print-layout"><Schematic template={template} building={building}/><aside>{template==='directions'?<><h2>{building.common_name}</h2><p><strong>{building.address}</strong></p><ol><li>Use the live campus map or external directions to reach UAF.</li><li>Follow posted campus wayfinding to {building.common_name}.</li><li>Check current parking restrictions before leaving your vehicle.</li><li>Use current UAF accessibility resources for verified accessible-entry information.</li></ol></>:template==='accessibility'?<><h2>Accessibility resources</h2><p>Use current UAF accessibility resources for verified facility information. Turn-by-turn accessible routing is not claimed in this pilot.</p><p>Accessible parking requires the appropriate UAF permit/decal in addition to an ADA permit.</p></>:template==='event'?<><h2>Event information</h2><div className="event-fields"><span>Event: __________</span><span>Date: __________</span><span>Venue: __________</span><span>Parking: ________</span><span>Drop-off: _______</span><span>Contact: ________</span></div></>:<><h2>Popular destinations</h2>{popularIds.slice(0,6).map(id=>{const b=campus.buildings.find(x=>x.id===id);return b?<p key={id}><strong>{b.common_name}</strong><br/>{b.address}</p>:null})}<h2>Visitor parking</h2>{visitor.map(p=><p key={p.id}><strong>{p.code} — {p.name}</strong><br/>{p.restrictions}</p>)}</>}</aside></div><footer><div><strong>University of Alaska Fairbanks</strong><br/>General info 907-474-7034 · Admissions 1-800-478-1823 · Emergency 911<br/>Map issues: uaf-web@alaska.edu</div><div className="north">↑<br/>North</div><QRCodeSVG value="https://www.uaf.edu/campusmap/" size={90} title="QR code to UAF campus map"/></footer></article>}
function Schematic({template,building}){const pts=campus.buildings.filter(exactPoint),minLat=64.849,maxLat=64.862,minLon=-147.855,maxLon=-147.812,xy=b=>[65+(b.longitude-minLon)/(maxLon-minLon)*870,560-(b.latitude-minLat)/(maxLat-minLat)*485],shown=template==='directions'?[building].filter(exactPoint):pts;return <div className="print-map" aria-label="Schematic campus map, not to scale"><svg viewBox="0 0 1000 620" role="img" aria-label="Schematic campus map, not to scale"><rect width="1000" height="620" fill="#f7f5e9"/><path d="M30 500 C260 430 620 470 970 420" className="road major"/><path d="M140 115 C350 150 585 145 870 90" className="road major"/><path d="M665 40 C655 235 695 365 905 515" className="road major"/><path d="M240 425 C420 345 610 315 820 332" className="road minor"/><text x="55" y="482">Tanana Loop</text><text x="715" y="72">Yukon Drive</text>{shown.map(b=>{const[x,y]=xy(b);return <g transform={`translate(${x},${y})`} key={b.id}><circle r="10" className="print-pin"/><text x="14" y="4">{b.abbreviation||b.common_name.slice(0,10)}</text></g>})}{template==='accessibility'&&<path d="M260 420 C420 350 570 320 740 270" className="access-route"/>}<text x="36" y="36" className="schematic-label">Schematic / not to scale</text></svg></div>}
