import React from 'react'
import {campus} from '../data/index.js'
import {ParkingCard} from './Cards.jsx'

export function ParkingPanel({onOpen}){return <><h2>Parking</h2><p className="callout">Current public UAF lot codes and restrictions are loaded. Exact lot polygons remain pending authoritative UAF GIS.</p><h3>Visitor payment zones</h3><div className="metric-grid">{campus.parking_policy.rates.map(r=><div key={r.zone} className="metric"><strong>Zone {r.zone}</strong><span>{r.description}</span><b>{r.rate}</b><small>{r.limit||''}</small></div>)}</div><p>{campus.parking_policy.visitor_note}</p><p><strong>Accessible parking:</strong> {campus.parking_policy.accessible_note}</p><p><a href={campus.parking_policy.source_url} target="_blank" rel="noreferrer">Open UAF Parking Services</a> · <a href="tel:+19074747384">907-474-7384</a></p><h3>Parking inventory</h3><div className="card-list">{campus.parking.map(p=><ParkingCard key={p.id} p={p} onOpen={onOpen}/>)}</div></>}
export function AccessPanel(){return <><h2>Accessibility</h2><p className="callout">Turn-by-turn accessible routing is intentionally not generated until UAF Facilities/GIS verifies entrances, walks, grades, ramps, stairs and barriers.</p><div className="link-stack"><a href={campus.accessibility.facilities_url} target="_blank" rel="noreferrer">UAF accessibility facilities</a><a href={campus.accessibility.current_restroom_map_url} target="_blank" rel="noreferrer">ADA / restroom map</a><a href={campus.accessibility.current_lactation_map_url} target="_blank" rel="noreferrer">Lactation / changing map</a><a href={campus.accessibility.parking_policy_url} target="_blank" rel="noreferrer">Accessible parking policy</a><a href={campus.accessibility.orca_url} target="_blank" rel="noreferrer">ADA / Section 504 information</a></div></>}
export function ShuttlePanel(){return <><h2>Shuttle</h2><p className="callout">UAF shuttles are ADA-equipped. BusWhere remains the live source for vehicle positions and ETAs.</p><div className="link-stack"><a className="primary-action" href={campus.shuttle.tracker_url} target="_blank" rel="noreferrer">Open live BusWhere tracker</a><a href={campus.shuttle.service_url} target="_blank" rel="noreferrer">Current shuttle schedules</a></div><h3>Public stop / area names</h3><ul className="simple-list">{campus.shuttle.stops.map(s=><li key={s}>{s}</li>)}</ul><p>Shuttle contact: <a href="tel:+19074746414">907-474-6414</a> · <a href="mailto:uaf-shuttles@alaska.edu">uaf-shuttles@alaska.edu</a></p></>}
export function TrailsPanel(){const t=campus.trails;return <><h2>North Campus trails</h2><div className="metric-grid"><div className="metric"><strong>{t.summary.total_miles}</strong><span>total miles listed</span></div><div className="metric"><strong>{t.summary.groomed_ski_miles}</strong><span>groomed ski miles</span></div><div className="metric"><strong>{t.summary.winter_walking_miles}</strong><span>winter walking miles</span></div><div className="metric"><strong>{t.summary.commuter_miles}</strong><span>commuter miles</span></div></div><div className="link-stack"><a className="primary-action" href={t.source_url} target="_blank" rel="noreferrer">Current trails & grooming</a><a href={t.winter_map_url} target="_blank" rel="noreferrer">Winter trail map PDF</a></div><div className="trail-list">{t.items.map((x,i)=><div className="trail-row" key={`${x.name}-${i}`}><strong>{x.name}</strong><span>{x.type}{x.distance_km?` · ${x.distance_km} km`:''}</span></div>)}</div><p>Trail issues: <a href="tel:+19074747000">907-474-7000</a> · <a href="mailto:uaf-fs-dispatch@alaska.edu">uaf-fs-dispatch@alaska.edu</a></p></>}
export function UpdatesPanel({onBuilding}){return <><h2>Construction & updates</h2><p className="callout">Project status is based on UAF's published 2026 schedule and is not a live closure or detour feed.</p><div className="card-list">{campus.construction.projects.map(p=>{const b=campus.buildings.find(x=>x.id===p.location_id);return b?<button type="button" className="result-card construction-card" key={p.id} onClick={e=>onBuilding(b,e)}><span><strong>{p.name}</strong><small>{p.status} · {p.scheduled_start} to {p.scheduled_end}</small><small>{p.description}</small></span></button>:<a className="result-card construction-card" key={p.id} href={campus.construction.source_url} target="_blank" rel="noreferrer"><span><strong>{p.name}</strong><small>{p.status} · {p.scheduled_start} to {p.scheduled_end}</small><small>{p.description}</small></span></a>})}</div><p><a href={campus.construction.source_url} target="_blank" rel="noreferrer">Open official 2026 construction map</a></p></>}
