import React from 'react'
import {Link} from 'react-router-dom'
import {campus} from '../data/runtime.js'
import {appleDirections,googleDirections,isVerifiedPoint} from '../lib.js'

const PlaceDialog=React.forwardRef(function PlaceDialog({building,parking,onClose},ref){
  const item=building||parking
  async function share(){
    const url=building?`${location.origin}/?place=${encodeURIComponent(building.id)}`:parking?`${location.origin}/?parking=${encodeURIComponent(parking.id)}`:location.href
    if(navigator.share){try{await navigator.share({title:building?.common_name||parking?.name||'UAF Campus Map',url});return}catch{}}
    try{await navigator.clipboard.writeText(url)}catch{}
  }
  return <dialog ref={ref} className="place-dialog" onClose={onClose} onCancel={e=>{e.preventDefault();onClose()}}>{item&&<><div className="dialog-head"><div><h2 tabIndex="-1" data-dialog-title>{building?building.common_name:`${parking.code} — ${parking.name}`}</h2><p>{building?building.address:'Parking information'}</p></div><button type="button" className="dialog-close" aria-label="Close place details" onClick={onClose}>×</button></div><div className="dialog-body">{building?<><dl className="info-grid"><div><dt>Category</dt><dd>{(building.category||'building').replaceAll('_',' ')}</dd></div><div><dt>Map point</dt><dd>{isVerifiedPoint(building)?'UAF-linked':'GIS verification pending'}</dd></div></dl>{building.services?.length>0&&<section><h3>Services and destinations</h3><p>{building.services.join(' · ')}</p></section>}<section><h3>Accessibility</h3><p>Use current UAF accessibility resources for verified facility and accessible-route information.</p><a href={campus.accessibility.facilities_url} target="_blank" rel="noreferrer">Open UAF accessibility facilities information</a></section>{building.recommended_parking?.length>0&&<section><h3>Suggested visitor parking starting point</h3>{building.recommended_parking.map(code=>{const p=campus.parking.find(x=>x.code===code);return p?<p key={code}><strong>{p.code} — {p.name}</strong><br/>{p.restrictions}</p>:null})}</section>}<section><h3>Source and feedback</h3><p>{building.source_url&&<><a href={building.source_url} target="_blank" rel="noreferrer">Open UAF building profile</a><br/></>}<a href={`mailto:${campus.meta.report_email}?subject=${encodeURIComponent(`Campus map correction: ${building.common_name}`)}`}>Report a map issue</a></p></section></>:<><section><h3>Current public restriction</h3><p>{parking.restrictions}</p></section><section><h3>Visitor payment guidance</h3><p>{campus.parking_policy.visitor_note}</p></section><section><h3>Boundary status</h3><p>Use posted signs for enforcement boundaries. Admin-drawn parking geometry is illustrative until authoritative UAF GIS is loaded.</p></section></>}</div><div className="dialog-actions"><a className="primary-action" href={googleDirections(item)} target="_blank" rel="noreferrer">Google directions</a><a href={appleDirections(item)} target="_blank" rel="noreferrer">Apple directions</a>{building&&<Link to={`/print?mode=selected&place=${encodeURIComponent(building.id)}`}>Print this area</Link>}<button type="button" onClick={share}>Share</button></div></>}</dialog>
})
export default PlaceDialog
